# Mastodon Comments
# For more information: https://github.com/feiju12138/mastodon-comments https://github.com/feiju12138/hexo-next-mastodon-comments
mastodon-comments:
  enable: false
  MASTODON_DOMAIN: mastodon.social # Mastodon 实例域名
  MASTODON_USER: feiju # Mastodon 实例中根评论发布的用户名
  # JS: https://cdn.jsdelivr.net/gh/feiju12138/mastodon-comments@4/dist/mastodon-comments.min.js # 自定义 JS 文件地址
